In [3]:
import numpy as np

In [4]:
total_reward = [2,4,5,1,2]

In [5]:
sample_probability = np.exp(total_reward)/np.sum(np.exp(total_reward)) #apply softmax to the total_reward list

In [6]:
sample_probability

array([0.03350929, 0.24760201, 0.67305204, 0.01232738, 0.03350929])

In [7]:
sample_probability.tolist()

[0.033509287852410155,
 0.247602007776674,
 0.6730520384293082,
 0.012327378089197647,
 0.033509287852410155]

In [9]:
np.random.choice(np.arange(0,len(sample_probability)),p = sample_probability)

1

In [10]:
np.arange(0,len(sample_probability))

array([0, 1, 2, 3, 4])

In [56]:
total_reward = [-1172.4941694426275, -1278.987912616467, -1774.9790325075703, -1182.9697257191438, -1547.1988237302185, -1303.708932372565, -1669.8492404595577, -1168.0471119639737, -1234.1706156102023, -1259.3038981673246]

In [57]:
total_reward

[-1172.4941694426275,
 -1278.987912616467,
 -1774.9790325075703,
 -1182.9697257191438,
 -1547.1988237302185,
 -1303.708932372565,
 -1669.8492404595577,
 -1168.0471119639737,
 -1234.1706156102023,
 -1259.3038981673246]

In [58]:
max(total_reward)

-1168.0471119639737

In [59]:
new_total_reward = []
for entry in total_reward:
    new_total_reward.append(np.log(entry*-1)*-1)

In [60]:
np.exp(total_reward)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [61]:
np.exp(new_total_reward)

array([0.00085288, 0.00078187, 0.00056339, 0.00084533, 0.00064633,
       0.00076704, 0.00059886, 0.00085613, 0.00081026, 0.00079409])

In [62]:
max(np.exp(new_total_reward))

0.000856129851062757

In [63]:
sum(np.exp(new_total_reward))

0.007516176301892668

In [65]:
(np.exp(new_total_reward))/np.sum(np.exp(new_total_reward))

array([0.11347295, 0.10402473, 0.07495659, 0.11246811, 0.08599178,
       0.10205221, 0.07967568, 0.11390497, 0.10780225, 0.10565073])

In [42]:
sample_probability = np.exp(total_reward)/np.sum(np.exp(total_reward)) #apply softmax to the total_reward list

/home/zuhao/anaconda2/envs/p37/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [43]:
sample_probability

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [66]:
total_reward = [-1172.4941694426275, -1278.987912616467, -1774.9790325075703, -1182.9697257191438, -1547.1988237302185, -1303.708932372565, -1669.8492404595577, -1168.0471119639737, -1234.1706156102023, -1259.3038981673246]

In [67]:
new_total_reward = []
for entry in total_reward:
    new_total_reward.append(np.log(entry*-1)*-1) #because the reward is negative here

sample_probability = (np.exp(new_total_reward))/np.sum(np.exp(new_total_reward)) #apply softmax to the

In [68]:
sample_probability

array([0.11347295, 0.10402473, 0.07495659, 0.11246811, 0.08599178,
       0.10205221, 0.07967568, 0.11390497, 0.10780225, 0.10565073])

In [69]:
np.argmin(sample_probability)

2