In [1]:
import trading_vix_and_spy

In [2]:
local_env = trading_vix_and_spy.trading_vix_and_spy()

In [3]:
local_env.index_feature_dataframe.iloc[100][-1][-1]

246.313324

In [4]:
local_env.index_feature_dataframe.iloc[100]

vix_price_adj_close                                                105.8
vix_adj_close                                                       10.7
mv_ratio                                                         5.09396
days_since_5                                                           1
days_since_6                                                          10
days_since_7                                                          78
spy_observation        [239.759613, 239.825241, 241.062866, 240.12524...
Name: 100, dtype: object

In [5]:
local_env.reset()

array([16.559998999999998, 4.421496369593475, 7, 11, 50,
       list([256.506134, 257.15640299999995, 257.062134, 258.306152, 262.801239, 262.471344, 260.775085, 259.43692000000004, 259.154175, 259.435242, 255.924973, 256.36016800000004, 255.868179, 249.472214, 244.1548, 250.834671, 246.567535, 245.838928, 248.980209, 243.606079, 246.728348, 249.368164, 251.336182, 245.734894, 246.945984, 250.872467, 249.557388, 251.610489, 250.872467, 252.935089]),
       0, 0], dtype=object)

In [6]:
local_env.index_feature_dataframe.iloc[100][1:].to_numpy()

array([10.7, 5.093964294843991, 1, 10, 78,
       list([239.759613, 239.825241, 241.062866, 240.125244, 240.547165, 239.356461, 239.665848, 241.625397, 240.725357, 241.100327, 241.419128, 241.512909, 242.319229, 242.69426, 242.52549700000003, 242.938004, 242.056717, 241.981644, 242.206711, 241.644165, 240.434677, 242.478592, 241.766022, 242.178558, 243.763062, 243.54747000000003, 244.10997000000003, 243.988129, 246.463333, 246.313324])],
      dtype=object)

In [7]:
import numpy as np

In [8]:
local_env.index_feature_dataframe.iloc[100][1:].to_numpy().shape

(6,)

In [9]:
observation = local_env.index_feature_dataframe.iloc[100][1:].to_numpy()

In [10]:
np.concatenate((observation,[0,0]),axis = 0)

array([10.7, 5.093964294843991, 1, 10, 78,
       list([239.759613, 239.825241, 241.062866, 240.125244, 240.547165, 239.356461, 239.665848, 241.625397, 240.725357, 241.100327, 241.419128, 241.512909, 242.319229, 242.69426, 242.52549700000003, 242.938004, 242.056717, 241.981644, 242.206711, 241.644165, 240.434677, 242.478592, 241.766022, 242.178558, 243.763062, 243.54747000000003, 244.10997000000003, 243.988129, 246.463333, 246.313324]),
       0, 0], dtype=object)

In [11]:
np.concatenate((observation,[0,0]),axis = 0).shape

(8,)

In [12]:
a = np.asarray([1,2,3])
a.shape

(3,)

In [13]:
a[0]

1

In [14]:
a[1]

2