In [ ]:
import numpy as np

In [ ]:
output_dim = 2
variance_for_exploration = 0.5

In [ ]:
inv_cov_matrix_diag = np.ones(output_dim)*variance_for_exploration
inv_cov_matrix = np.diag(inv_cov_matrix_diag)

In [ ]:
inv_cov_matrix

In [ ]:
from sklearn.kernel_approximation import RBFSampler

In [ ]:
rbf_feature = RBFSampler(gamma=1, n_components = 10, random_state=12345)

In [ ]:
rbf_feature.fit_transform(np.asarray([1,2,3]).reshape(1, -1))

In [ ]:
rbf_feature.fit_transform(np.asarray([1,2,3]).reshape(1, -1))

In [10]:
import trading_vix

In [11]:
env = trading_vix.trading_vix()

In [12]:
env.reset().shape

(6, 1)

In [4]:
env.reset()

array([[28.08      ],
       [ 4.50504212],
       [ 8.        ],
       [19.        ],
       [71.        ],
       [ 0.        ]])

In [5]:
import gym

In [6]:
env = gym.make('Pendulum-v0')

In [8]:
env.reset().shape

(3,)

In [14]:
import numpy as np
a = [3]
a = np.asarray(a).reshape(1,1)

In [15]:
a

array([[3]])

In [16]:
a[0][0]

3

In [24]:
mean_action = np.asarray([3]).reshape(1,1)
mean_action

array([[3]])

In [25]:
from torch.distributions import MultivariateNormal
import torch

mean_action = np.asarray([3]).reshape(1,1)
mean_action = torch.tensor(mean_action)
variance = torch.full(size=(1,), fill_value=0.5)
cov_matrix = torch.diag(variance)

dist = MultivariateNormal(mean_action, cov_matrix)

In [26]:
dist

MultivariateNormal(loc: tensor([[3]]), covariance_matrix: tensor([[[0.5000]]]))

In [27]:
from scipy.stats import multivariate_normal

In [28]:
multivariate_normal.rvs(mean=mean_action, cov=0.5)

3.747373376201773

In [30]:
a = np.asarray([1,3])

In [31]:
a/np.sum(a)

array([0.25, 0.75])

In [32]:
import gym
env = gym.make('LunarLanderContinuous-v2')

In [34]:
np.log(1000)

6.907755278982137

In [35]:
np.exp(np.log(1000))

999.9999999999998