In [1]:
import numpy as np

In [2]:
output_dim = 2
variance_for_exploration = 0.5

In [3]:
inv_cov_matrix_diag = np.ones(output_dim)*variance_for_exploration
inv_cov_matrix = np.diag(inv_cov_matrix_diag)

In [4]:
inv_cov_matrix

array([[0.5, 0. ],
       [0. , 0.5]])

In [5]:
from sklearn.kernel_approximation import RBFSampler

In [19]:
rbf_feature = RBFSampler(gamma=1, n_components = 10, random_state=12345)

In [20]:
rbf_feature.fit_transform(np.asarray([1,2,3]).reshape(1, -1))

array([[ 0.26976153,  0.41818633, -0.39139828, -0.42776298,  0.30630762,
        -0.01641867,  0.43722318, -0.40191946, -0.43061401,  0.24375861]])

In [21]:
rbf_feature.fit_transform(np.asarray([1,2,3]).reshape(1, -1))

array([[ 0.26976153,  0.41818633, -0.39139828, -0.42776298,  0.30630762,
        -0.01641867,  0.43722318, -0.40191946, -0.43061401,  0.24375861]])